/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedDraftsIndexRouteImport } from './routes/_authenticated/drafts/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedDraftsDraftIdRouteImport } from './routes/_authenticated/drafts/$draftId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat/$threadId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsIndexRoute =
  AuthenticatedDraftsIndexRouteImport.update({
    id: '/drafts/',
    path: '/drafts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsDraftIdRoute =
  AuthenticatedDraftsDraftIdRouteImport.update({
    id: '/drafts/$draftId',
    path: '/drafts/$draftId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/drafts/$draftId': typeof AuthenticatedDraftsDraftIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/drafts/': typeof AuthenticatedDraftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/drafts/$draftId': typeof AuthenticatedDraftsDraftIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/drafts': typeof AuthenticatedDraftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/drafts/$draftId': typeof AuthenticatedDraftsDraftIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/drafts/': typeof AuthenticatedDraftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intake'
    | '/api/chat'
    | '/chat/$threadId'
    | '/drafts/$draftId'
    | '/chat/'
    | '/drafts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intake'
    | '/api/chat'
    | '/chat/$threadId'
    | '/drafts/$draftId'
    | '/chat'
    | '/drafts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/intake'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/drafts/$draftId'
    | '/_authenticated/chat/'
    | '/_authenticated/drafts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts/': {
      id: '/_authenticated/drafts/'
      path: '/drafts'
      fullPath: '/drafts/'
      preLoaderRoute: typeof AuthenticatedDraftsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts/$draftId': {
      id: '/_authenticated/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof AuthenticatedDraftsDraftIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedDraftsDraftIdRoute: typeof AuthenticatedDraftsDraftIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedDraftsIndexRoute: typeof AuthenticatedDraftsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedDraftsDraftIdRoute: AuthenticatedDraftsDraftIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedDraftsIndexRoute: AuthenticatedDraftsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
